-- Supabase schema for confession app
-- Matches tables used by src/App.js

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password_hash text not null,
  last_login_at timestamptz,
  login_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_users_email_check check (length(trim(email)) > 0)
);

create table if not exists public.app_auth_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  event_type text not null check (event_type in ('sign_up', 'log_in')),
  event_at timestamptz not null default now()
);

create index if not exists idx_app_auth_events_user_id_event_at
  on public.app_auth_events (user_id, event_at desc);

create or replace function public.app_sign_up(p_email text, p_password text)
returns table(user_id uuid, email text)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_email text := lower(trim(p_email));
begin
  if coalesce(length(normalized_email), 0) = 0 then
    raise exception 'Email is required';
  end if;

  if coalesce(length(p_password), 0) < 8 then
    raise exception 'Password must be at least 8 characters';
  end if;

  insert into public.app_users (email, password_hash, updated_at)
  values (normalized_email, extensions.crypt(p_password, extensions.gen_salt('bf')), now())
  returning app_users.id, app_users.email into user_id, email;

  insert into public.app_auth_events (user_id, event_type)
  values (user_id, 'sign_up');

  return next;
exception
  when unique_violation then
    raise exception 'Username already exists';
end;
$$;

create or replace function public.app_log_in(p_email text, p_password text)
returns table(user_id uuid, email text)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_email text := lower(trim(p_email));
  matched_user_id uuid;
begin
  select u.id, u.email
  into matched_user_id, email
  from public.app_users u
  where u.email = normalized_email
    and u.password_hash = extensions.crypt(p_password, u.password_hash)
  limit 1;

  if matched_user_id is null then
    raise exception 'Invalid email or password';
  end if;

  update public.app_users
  set
    last_login_at = now(),
    login_count = login_count + 1,
    updated_at = now()
  where id = matched_user_id;

  insert into public.app_auth_events (user_id, event_type)
  values (matched_user_id, 'log_in');

  user_id := matched_user_id;
  return next;
end;
$$;

create table if not exists public.share_status (
  share_id text primary key,
  received boolean not null default false,
  viewed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  share_id text not null,
  role text not null check (role in ('sender', 'receiver')),
  text text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_messages_share_id_created_at
  on public.chat_messages (share_id, created_at);

create table if not exists public.drafts (
  draft_key text primary key,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null,
  email text,
  page text,
  created_at timestamptz not null default now()
);
